import { ThemeProvider } from '@/lib/providers/next-theme-provider';
import db from '@/lib/supabase/db';
import type { Metadata } from 'next';
import { DM_Sans, Inter } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import './globals.css';

console.log('🚀 ~ file: layout.tsx:5 ~ db:', db);

const inter = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={twMerge('bg-background', inter.className)}>
        <ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
